### PR TITLE
support staging to INSTALL_MOD_PATH

### PR DESCRIPTION
**Pull request by crorvick**
Add support for module trees installed to a staging area via INSTALL_MOD_PATH.

### CODE REVIEW

**Comment by aalemayhu** [comment]
Could you change your prefix in the commit from `bus1:` to `build:`, even better `Makefile:` IMO?

**Comment by dvdhrm** [comment]
Both look good, thanks! I advise against `make (un)install` in packagers, though. It is usually easier to copy the `*.ko` manually to your location of choice.

Applied. Thanks!

**Comment by crorvick** [comment]
On Sat, Dec 10, 2016 at 08:45:41AM -0800, David Herrmann wrote:
> Both look good, thanks! I advise against `make (un)install` in
> packagers, though. It is usually easier to copy the `*.ko` manually to
> your location of choice.

I test kernels on my laptop and use a separate host for building.  I was
just using this to build and install the bus1 module before creating the
tarball.  I guess this is a primitive packager, but it was convenient to
have the `install` target use $(INSTALL_MOD_PATH) for this workflow.

Given that, would you still advise against using `install`?  While
copying the module into place isn't hard, having `install` DWIM made it
a pretty brainless activity.  What are the downsides of using `install`?

> Applied. Thanks!

Cool, thanks!

Regards,

Chris

**Comment by dvdhrm** [comment]
`install` is fine for developers. Only if you intend to package the module, I recommend using your own install-script adjusted to your needs.

**Pull request merged**
