### PR TITLE
handle minor API changes up to kernel 4.14

### PR DESCRIPTION
**Pull request by edef1c**
This replaces `GFP_TEMPORARY` with `GFP_KERNEL` unconditionally, and handles the flags argument for `vfs_iter_write` conditional on kernel version. I hope I got the commit format right.

### CODE REVIEW

**Comment by dvdhrm** [comment]
Both look good. Though, I cannot cherry-pick them, unless you provide a a signed-off-by line. This is meant for upstream inclusion, so we need sign-offs. See here:

https://developercertificate.org/

To fullfill this, simply reply here with:

Signed-off-by: $name <$email>

**Comment by dvdhrm** [comment]
Oh, forgot to mention: You're not obliged to provide this information. I can push my own variants of both fixes, if you prefer.

**Comment by edef1c** [comment]
Signed-off-by: edef <edef@edef.eu>

**Comment by edef1c** [comment]
I've fixed up the commits to include that — didn't do so previously because I assumed it had a different purpose.

**Comment by JoelStienlet** [comment]
Hello! I've just encountered the same problem, as I see it's already patched and working thank you!
Is there anything precluding the patch from being merged now?

**Comment by dvdhrm** [comment]
I pushed required fixes myself now. Note that we don't support older kernels for the out-of-tree module. Hence, the kernel-version check is not needed. We always require the latest stable kernel as source.

Lastly, we really have the same requirements for patch submissions as the upstream kernel. This means a real-name + signoff. I now patched the source in question myself.

Thanks a lot for the hints! Everything should work fine with 4.14 now.

**Comment by edef1c** [comment]
…this is my real name, sufficiently so that I could own a UK passport with it if I paid the fee. what the fuck.

**Comment by dvdhrm** [comment]
Errrr, ok? I am fine with that. Not sure what the problem is.
I forward-ported the module myself, since `make tt` (which runs the test-suite) failed with your patches applied, and that made me suspicious. I think the result is almost the same as your patches, but with the added KERNEL_DS fix, isn't it?

**Comment by edef1c** [comment]
> Lastly, we really have the same requirements for patch submissions as the upstream kernel. This means a real-name + signoff. I now patched the source in question myself.

Given that I got a "looks good, just needs Signed-off-by", and after I added that, all I got was a week and a half of radio silence, followed by this comment and a PR close, I'm really unsure how else I should've interpreted it.
I'm obviously fine with the patch, given that it is identical to what I submitted once you strip the preprocessor directives.

**Comment by dvdhrm** [comment]
> I'm really unsure how else I should've interpreted it.

I took the quick and easy approach and did the forward-porting myself, rather than resolving the issues through conversation. This was inconsiderate and rude. I apologize. It was not my intention, and it was a shortsighted action. I am sorry!

**Comment by edef1c** [comment]
Ah, okay, no worries! I'll make sure to take care of the `Signed-off-by` in the future (I only learnt about `git commit -s` afterwards), and I'll make sure to run the test suite next time too (is `make tt` documented somewhere?)

**Pull request closed without merging**
