### PR TITLE
Fix compatibility with upcoming 4.11 kernel

### PR DESCRIPTION
**Pull request by tpruzina**
RFC, please checkout commit descriptions for details.

Kernel related change happened here:
https://github.com/torvalds/linux/commit/10383aea2f445bce9b2a2b308def08134b438c8e

### CODE REVIEW

**Comment by dvdhrm** [comment]
Hm. TBH, I don't like the version-checking... I'd rather either make a hard cut and support only v4.11 onwards.. or preferably just drop the ref-count tests.

I'm leaning towards the latter... @teg, any comments?

**Comment by teg** [comment]
I agree. Would be ok to depend on a newer  kernel for something important, but this does not seem worth the hassle. Dropping these checks from the tests seem fine by me.

**Comment by dvdhrm** [comment]
@tpruzina : Please remember to provide your Signed-off-by line for every kernel patch.

Regarding the patches: I fixed both now. The creds.h include needed some more adjustments, so I pushed them as well. And I decided against dropping the kref-verification, since it is crucial in our handle-tests. Instead, I decided to use the new kref_read() function, and provide a fallback until v4.11 is released.

Thanks for the report!

**Comment by tpruzina** [comment]
Fair enough, cheers.

**Pull request closed without merging**
